### ISSUE TITLE
are you able to get new (u15) flat ones?

### ISSUE THREAD

**Issue by idontveapc** [popemkt/segoe-ui-emoji#1]

**Comment by idontveapc** [comment]
use this branch: https://github.com/microsoft/fluentui-emoji/tree/williamch/emoji15

has last year's u15 emojis but other updated emojis aren't there, even neither the main branch. emojipedia.org has all chnaged and new though.

**Comment by popemkt** [comment]
Thanks @idontveapc , I was actually using that branch.

**Comment by popemkt** [comment]
Closed as the https://github.com/popemkt/segoe-ui-emoji/blob/main/self-compiled.ttf file should contain all emojis from the branch mentioned in https://github.com/popemkt/segoe-ui-emoji/issues/1#issuecomment-1862192181.
